version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dqo
      POSTGRES_PASSWORD: dqo
      POSTGRES_DB: dqo
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
